### ISSUE TITLE
Impossible to construct Moray ammo

### ISSUE THREAD

**Issue by Starwaster** [Blaylock1988/VanillaReplacement-GV-Weapons-Pack#36]
It is impossible to construct Moray ammo because the ammo requires 10,000 liters and the Assembler only has 4,000 liters of inventory space

**Comment by Blaylock1988** [comment]
oh interesting! I never thought of that connection, check the other big ammos too like MAC and Shiva

**Comment by Blaylock1988** [comment]
Fixed by increasing assembler inventory size to 10k
